# Generated by Django 2.0.5 on 2018-07-22 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likecount',
            old_name='likednum',
            new_name='liked_num',
        ),
    ]
